### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by holyghost1** [jafigueroa-dev/lol-account-checker#1]
Traceback (most recent call last):
  File "c:\Users\holyghost\Desktop\lol-account-checker\lolchecker.py", line 196, in <module>
    print(account_checker.print_info())
  File "c:\Users\holyghost\Desktop\lol-account-checker\lolchecker.py", line 167, in print_info
    inventory_data = self.get_inventory()
  File "c:\Users\holyghost\Desktop\lol-account-checker\lolchecker.py", line 95, in get_inventory
    result = response.json()['data']['items']
KeyError: 'data'

**Comment by AliHaider20** [comment]
The response must not be having data as a key. You need to check out the error as I don't have a LOL account.
Update the code like this:
Step 1:
      result = response.json()
      print(data)
Step 2:
      result[the key]['items']

I hope I'm able to explain the above error. If not you can write me a msg.

**Comment by holyghost1** [comment]
> The response must not be having data as a key. You need to check out the error as I don't have a LOL account.
> Update the code like this:
> Step 1:
> result = response.json()
> print(data)
> Step 2:
> result[the key]['items']
> 
> I hope I'm able to explain the above error. If not you can write me a msg.

How can i msg you?

**Comment by jafigueroa-dev** [comment]
Try putting the following print statement in the get_inventory method to see the response:

```python
 response = self.session.get(url=URL)
 print(response.json())
 result = response.json()['data']['items']
```

For some reason, the response you're getting from that account doesn't have a 'data' key in it (so no data retrievable). Seems like a problem with the account but print the response to make sure.

**Comment by AliHaider20** [comment]
> > The response must not be having data as a key. You need to check out the error as I don't have a LOL account.
> > Update the code like this:
> > Step 1:
> > result = response.json()
> > print(data)
> > Step 2:
> > result[the key]['items']
> > I hope I'm able to explain the above error. If not you can write me a msg.
> 
> How can i msg you?

You can msg here what is the problem you're facing after the above solution.
