### ISSUE TITLE
how to avoid getting rate limited?

### ISSUE THREAD

**Issue by blesphy1** [jafigueroa-dev/lol-account-checker#6]
when this checker works it's perfect but a lot of the time i'll just get rate limited instantly and locked out from checking or logging into any accounts for like 15-20 min, is there a way to avoid this? perhaps some way to set a limit on how fast the checker will attempt logins, or the addition of proxies to the checker.

thanks for your work

**Comment by jesus-figueroa** [comment]
I'm looking into adding proxy support soon.

**Comment by jafigueroa-dev** [comment]
Just updated the script, optimized it and added a timeout to avoid rate limiting. Try it out now.

**Comment by blesphy1** [comment]
thanks man!!

**Comment by blesphy1** [comment]
just used the checker with your latest update--works perfectly and all problems from before are solved. great work bro
